/**
 * MOS (Moment of Symmetry) scales — generated scales with exactly two step sizes.
 * Used in xenharmonic / microtonal theory to find well-formed scales in arbitrary EDOs.
 */

export class MOS {
  /**
   * Generates a MOS scale by stacking a generator interval within a period.
   *
   * @param generator - Generator size in steps within the period.
   * @param period - Period size in steps (usually octave = 12 in 12-TET, or EDO divisions).
   * @param size - Number of notes desired.
   * @returns Array of step offsets from 0 (the tonic), sorted ascending.
   */
  static generate(generator: number, period: number, size: number): number[] {
    if (size <= 0 || period <= 0) return [];
    const pcs = new Set<number>();
    let pos = 0;
    for (let i = 0; i < size; i++) {
      pcs.add(((pos % period) + period) % period);
      pos += generator;
    }
    return Array.from(pcs).sort((a, b) => a - b);
  }

  /**
   * Tests whether a set of steps constitutes a MOS scale:
   * a scale with exactly two different step sizes, generated by a single interval.
   *
   * @param scale - Array of step offsets (must include 0).
   * @returns true if the scale is a MOS (well-formed scale).
   */
  static isMOS(scale: number[]): boolean {
    if (scale.length < 2) return false;
    const sorted = [...scale].sort((a, b) => a - b);

    // Compute intervals between consecutive degrees
    const intervals: number[] = [];
    for (let i = 1; i < sorted.length; i++) {
      intervals.push(sorted[i] - sorted[i - 1]);
    }
    // Include wrap-around interval (assumes period is max+step)
    // We infer period as the max value + smallest interval
    const minStep = Math.min(...intervals);
    const period = sorted[sorted.length - 1] + minStep;
    intervals.push(period - sorted[sorted.length - 1]);

    const unique = new Set(intervals);
    return unique.size === 2;
  }

  /**
   * Returns the MOS family — all MOS scales for a given generator and period up to maxSize.
   * Each entry is a MOS scale (sorted step array).
   */
  static getMOSFamily(generator: number, period: number, maxSize: number): number[][] {
    const result: number[][] = [];
    for (let size = 2; size <= maxSize; size++) {
      const scale = this.generate(generator, period, size);
      if (this.isMOS(scale)) {
        result.push(scale);
      }
    }
    return result;
  }
}

/**
 * Comma pump detection in just intonation progressions.
 */
import { Chord } from './chord';
import { JustIntonation } from './tuning';

export class CommaPump {
  /**
   * Detects if a chord progression drifts in pitch due to JI comma accumulation.
   *
   * Returns the total drift in cents and the likely comma type.
   * A drift near 0 means the progression is comma-free ("pumpless").
   * A drift near a known comma value identifies the pump type.
   *
   * @param chords - The progression (all chords should share the same JI tuning).
   * @param tuning - The JI tuning context.
   */
  static detect(
    chords: Chord[],
    tuning: JustIntonation
  ): { drift: number; commaType?: 'syntonic' | 'pythagorean' | 'septimal' } {
    if (chords.length < 2) return { drift: 0 };

    // Sum up the pitch drift: consecutive root intervals
    let totalCents = 0;
    for (let i = 1; i < chords.length; i++) {
      const diff = chords[i].rootStep - chords[i - 1].rootStep;
      totalCents += tuning.getInterval(diff).cents;
    }

    // Return to root: add the final interval back to start
    const loopCents = totalCents + tuning.getInterval(chords[0].rootStep - chords[chords.length - 1].rootStep).cents;
    const drift = Math.abs(loopCents);

    // Known commas in cents
    const SYNTONIC = 21.5; // 81/80
    const PYTHAGOREAN = 23.5; // 531441/524288
    const SEPTIMAL = 35.7; // 64/63

    let commaType: 'syntonic' | 'pythagorean' | 'septimal' | undefined;
    if (Math.abs(drift - SYNTONIC) < 3) commaType = 'syntonic';
    else if (Math.abs(drift - PYTHAGOREAN) < 3) commaType = 'pythagorean';
    else if (Math.abs(drift - SEPTIMAL) < 5) commaType = 'septimal';

    return { drift, commaType };
  }
}
